version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: etsy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etsydb
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: postgres://etsy:password@db/etsydb
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
volumes:
  pgdata: